const articles = [
    {
        title: 'Ancient Civilizations of Mesopotamia: From Sumer to Babylon',
        article: 'Ancient civilizations of Mesopotamia, particularly Sumer, Akkad, Assyria, and Babylon, are considered some of the first in world history. They emerged in the region between the Tigris and Euphrates rivers, where favorable conditions allowed people to transition to a settled way of life. Sumer, in particular, was renowned for its developed writing system known as cuneiform. This innovation laid the foundation for keeping records, legal documents, and literature. Sumer also saw the rise of the first city-states, such as Ur and Lagash, which became centers of trade and culture. Babylon, which emerged in the middle period of Mesopotamia, also left a significant mark on history. The Code of Hammurabi, one of the oldest known legal codes, established the foundations of justice. Babylon was noted for its magnificent architecture, particularly the famed Hanging Gardens, which are considered one of the Seven Wonders of the Ancient World. The cultural legacy of Mesopotamia influenced the development of other civilizations. It laid the groundwork for sciences such as astronomy and mathematics and was pivotal in shaping future cultures, including ancient Greece and Rome.',
        image: require('../assets/articles/1.png')
    },
    {
        title: 'The Role of Religion in Shaping Civilizations: Faith and Identity',
        article: 'Religion played a crucial role in shaping the social structures and cultures of various civilizations. From ancient Egypt to India, religious beliefs defined not only personal faith but also political, economic, and social relations within societies. In Egypt, for instance, religion was closely tied to political power. Pharaohs were considered divine beings, and their authority was legitimized through religious rituals. The pyramids, serving as tombs for pharaohs, illustrate the significance of religion in the life and death of Egyptians. In ancient India, religion also played a vital role in shaping the social hierarchy through the caste system. Hinduism, with its numerous deities and rituals, permeated every aspect of people`s lives. Similarly, Buddhism, which emerged in India, influenced many cultures across East Asia, altering religious practices and worldviews. Thus, religious beliefs not only shaped culture and social structures but also fostered national identity, impacting the development of art, science, and philosophy.',
        image: require('../assets/articles/2.png')
    },
    {
        title: 'The Aztecs and Their Culture: Pyramids, Religion, and Heritage',
        article: 'The Aztecs, who flourished in Central Mexico during the 15th and 16th centuries, left a significant mark on history. Their culture was characterized by a complex social structure and advanced architecture. Pyramids, such as those in Tenochtitlan, housed temples dedicated to deities central to their religion. Aztec religion was polytheistic, with numerous gods, such as Huitzilopochtli, the god of war and the sun. Religious rituals, including sacrifices, were essential for ensuring the well-being and prosperity of society. These ceremonies not only emphasized their beliefs but also strengthened social unity. The legacy of the Aztec civilization can still be seen today in Mexican culture. Many traditions, rituals, and artistic elements trace their roots back to Aztec origins. Modern Mexicans continue to celebrate festivals and preserve customs related to their Aztec heritage, maintaining a connection to their historical past.',
        image: require('../assets/articles/3.png')
    },
    {
        title: 'Byzantium: Preserving Ancient Heritage in the Middle Ages',
        article: 'The Byzantine Empire, which existed from the 4th to the 15th century, played a crucial role in preserving ancient heritage during the Middle Ages. The Byzantines safeguarded and transmitted knowledge, art, and literature from the ancient world, which became the foundation for the Renaissance. Through libraries and universities, such as the University of Constantinople, Byzantine scholars preserved classical works from Greece and Rome, as well as developed new ideas in science, philosophy, and theology. They wrote numerous commentaries on ancient texts, helping to maintain this knowledge for future generations. Byzantine architecture continued the traditions of ancient art, particularly through the construction of cathedrals like Hagia Sophia in Constantinople. These structures reflect a fusion of Greek, Roman, and Eastern styles, showcasing the cultural diversity of the empire. Thus, Byzantium served as an important bridge between antiquity and the modern era, preserving and developing cultural heritage that influenced the formation of European civilization.',
        image: require('../assets/articles/4.png')
    },
    {
        title: 'Indian Civilizations: From Harappa to Modernity',
        article: 'Indian civilizations have a long and diverse history spanning thousands of years. From the Indus Valley civilization of Harappa, which thrived around 2500 BCE, to modern times, India has experienced numerous cultural and religious transformations. The Harappan civilization was characterized by high levels of urbanization, advanced architecture, and irrigation systems. Over time, with the emergence of Vedic culture, the foundations of Hinduism were laid, shaping the social and religious structure of India. Throughout the millennia, India has been home to various religions, including Buddhism and Jainism. These religions not only influenced Indian culture but also spread across Asia. Modern India continues to embrace this cultural diversity, showcasing the richness of its traditions through art, music, and literature. In conclusion, Indian civilizations continue to impact the world, preserving their uniqueness and cultural heritage in contemporary society.',
        image: require('../assets/articles/5.png')
    },
    {
        title: 'Medieval European Civilizations: From Feudalism to the Renaissance',
        article: 'The Middle Ages, spanning roughly from the 5th to the 15th century, was a time of significant political and social change in Europe. Feudalism, as the primary social and economic structure, defined the lives of most people, where vassals served their lords in exchange for land and protection. However, in the 14th century, the rise of towns and trade led to changes in society. Capitalism gradually began to replace feudal relations, creating new social classes such as the bourgeoisie. This shift resulted in the emergence of new ideas and movements that contributed to the cultural revival. The Renaissance, beginning in the 15th century, was a product of these changes. It was marked by a renewed interest in antiquity, the development of science, art, and literature. Important figures like Leonardo da Vinci and Michelangelo shaped a new cultural landscape that defined European identity. Thus, the political and social changes of the medieval period had a decisive influence on the further development of Europe, laying the groundwork for modern democratic values.',
        image: require('../assets/articles/6.png')
    },
    {
        title: 'The Influence of Ancient Chinese Dynasties on World History',
        article: 'Ancient Chinese dynasties, such as Shang, Zhou, Han, and Tang, significantly impacted the development of world history through their achievements in science, technology, and philosophy. Inventions such as paper, gunpowder, and the compass changed not only China but also the world, facilitating trade and military technology. The philosophy that developed in China also left a noticeable mark. Confucianism, Daoism, and Buddhism became fundamental teachings that shaped moral values, social relations, and political thought. These philosophical traditions deeply influenced neighboring countries such as Korea, Japan, and Vietnam. The imperial governance system that arose in China laid the foundations for many governmental structures in other nations. Administrative practices, such as civil service, were adopted and adapted in various parts of the world. Thus, the ancient Chinese dynasties made significant contributions to the development of world civilization, continuing to influence the modern world through their cultural, scientific, and social achievements.',
        image: require('../assets/articles/7.png')
    },
    {
        title: 'Women in the History of Civilizations: Role and Influence in Different Eras',
        article: 'Women have played important roles in the development of civilizations, although their contributions often went unnoticed by historians. Throughout different eras, women engaged not only in domestic affairs but also actively participated in political, social, and cultural processes. In ancient civilizations such as Egypt and Mesopotamia, women had certain rights, particularly in property and inheritance. Women like Hatshepsut, a female pharaoh of Egypt, demonstrated that women could hold high positions and influence politics. In the medieval period, women also played a significant role in social change. They were active participants in religious movements and contributed to the development of art and science. For instance, Gidona Philosopher in Germany became a notable figure in Christian philosophy. In the modern world, women`s roles in society continue to evolve. Women actively fight for their rights, engaging in politics and the economy, influencing the formation of new social norms. Their contributions to the development of civilizations are undeniable and continue to leave a mark on history.',
        image: require('../assets/articles/8.png')
    },
    {
        title: 'Civilizations of South America: The Incas and Their Legacy',
        article: 'The Inca civilization, which flourished in South America during the 15th and 16th centuries, was one of the largest and most powerful in the world. They created a complex social structure and a robust economy based on agriculture, particularly the cultivation of potatoes and corn. The Incas also achieved significant architectural advancements. Their massive structures, such as Machu Picchu and Sacsayhuamán, showcase their stone-working skills and understanding of geography. These buildings served not only religious functions but also as centers of administration. Inca religion was polytheistic, with numerous deities reflecting the forces of nature. Their religious rituals, including sacrifices, illustrate how belief influenced society and culture. The legacy of the Incas continues to thrive in modern Peru. Their traditions, agriculture, and cultural practices have been preserved and adapted over the centuries. Incan heritage has become an essential part of Peruvian identity, shaping the modern culture of the country.',
        image: require('../assets/articles/9.png')
    },
    {
        title: 'Globalization: How Historical Trade Routes Changed the World',
        article: 'Globalization, which began in ancient times, resulted from the development of trade routes that connected different cultures and civilizations. The Silk Road, for example, was an important trade route linking China with Europe, allowing for the exchange of goods, ideas, and technologies. These routes not only facilitated economic development but also became platforms for cultural exchange. Through them, religions such as Buddhism and Islam spread, as did new scientific knowledge and technological innovations. This led to the creation of new cultural and social traditions. Trade routes also significantly impacted political relations between countries. They contributed to the formation of empires and new states, altering the world`s map. Contacts between different peoples led to increased interdependence, which is characteristic of modern globalization. Thus, historical trade routes played a key role in shaping the modern world, contributing to the development of the global economy and cultural diversity.',
        image: require('../assets/articles/10.png')
    }
];

export default articles;